### ISSUE TITLE
How do you want to handle handicap stones?

### ISSUE THREAD

**Issue by Trevoke** [kendfrey/ankifu#1]
This is a great concept!

I tried this with my favorite game record ever - Dosaku's Masterpiece - which is a two-stone handicap game, and it's very weird to try to replay this when the handicap stones are missing :D

**Comment by kendfrey** [comment]
You're right, I should have considered that some pro games actually did give handicap.

For now it should work if you edit the SGF to give black multiple moves in a row (with or without W passes).

I'll look into adding handicap support directly. Most likely they would be treated as ordinary moves when studying.

**Comment by kendfrey** [comment]
Completed in https://github.com/kendfrey/ankifu/commit/eb7ebd6098e6396b2829c837392ce66c9c0a4080. Note that this doesn't affect existing games, you'll have to reimport.

**Comment by Trevoke** [comment]
Amazing, thank you!

--

Aldric.
